# Generated by Django 4.1 on 2024-01-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InvertedCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100)),
                ("speech_indices", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="MemberKeywords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("member_name", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("keywords", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="PartyKeywords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("political_party", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("keywords", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SimilarMembers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("member_name", models.CharField(max_length=100)),
                ("similar_members", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Speech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("member_name", models.CharField(max_length=100)),
                ("political_party", models.CharField(max_length=100)),
                ("sitting_date", models.IntegerField()),
                ("speech", models.TextField()),
                ("processed_speech", models.TextField()),
            ],
        ),
    ]
