# Generated by Django 4.1 on 2024-02-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("IRWebApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SVD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("speech_indices", models.IntegerField()),
                ("speech_keywords", models.TextField()),
            ],
        ),
    ]
