# Generated by Django 4.1 on 2024-02-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("IRWebApp", "0002_svd"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimilarSpeeches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("speech_index", models.IntegerField()),
                ("speech_signature", models.IntegerField()),
            ],
        ),
    ]
