# Generated by Django 4.1 on 2024-02-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("IRWebApp", "0003_similarspeeches"),
    ]

    operations = [
        migrations.RenameField(
            model_name="similarspeeches",
            old_name="speech_signature",
            new_name="speech_similar_1_index",
        ),
        migrations.AddField(
            model_name="similarspeeches",
            name="speech_similar_2_index",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="similarspeeches",
            name="speech_similar_3_index",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
